server:
  port: 5000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: vendor-service
          uri: http://localhost:5002
          predicates:
            - Path=/api/vendors/**
        - id: product-service
          uri: http://localhost:5003
          predicates:
            - Path=/api/products/**, /api/categories/**, /api/reviews/**
        - id: order-service
          uri: http://localhost:5004
          predicates:
            - Path=/api/orders/**, /api/order-items/**
        - id: user-service
          uri: http://localhost:5001
          predicates:
            - Path=/api/users/**

jwt:
  token:
    secret: 4pP7cZ9XVlgWZ2aVUbKN1ZnTgLs5pZIsLmbbAqJrFiA=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5005/eureka/
    register-with-eureka: true
    fetch-registry: true
